from tkinter import *
root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
img=PhotoImage(file="//192.168.4.11/211b076/AP/PROJECT AP/Bus_for_project.png")
home=PhotoImage(file="//192.168.4.11/211b076/AP/PROJECT AP/home.png")
Label(root,image=img).grid(row=0,column=1,columnspan=11,pady=20)
Label(root,text='Online Bus Booking System',font='Arial 14 bold', bg='cadetblue1',fg='red').grid(row=1,column=1,columnspan=11)
Label(root,text='Add Bus Route Details',font='Arial 14 bold',fg='green4').grid(row=2,column=1,columnspan=11,pady=20)
Label(root,text='Route Id').grid(row=4,column=0,padx=(250,0),pady=40)
Entry(root).grid(row=4,column=1,padx=10)
Label(root,text='Station Name').grid(row=4,column=2)
Entry(root).grid(row=4,column=3,padx=10)
Label(root,text='Station Id').grid(row=4,column=4)
Entry(root).grid(row=4,column=5,padx=10)
Label(root,text='').grid(row=4,column=6)
Label(root,text='').grid(row=4,column=7,padx=10)
Label(root,text='').grid(row=4,column=8)
Label(root,text='').grid(row=4,column=9,padx=10)
Button(root,text='Add Route',bg='SpringGreen2').grid(row=4,column=10)
Button(root,text='Delete Route',bg='SpringGreen2',fg='red').grid(row=4,column=11,padx=10)
def fun():
    root.destroy()
    import home_page
Button(root,image=home,command=fun).grid(row=5,column=8)
