from tkinter import*
from tkinter.messagebox import*
root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
bus=PhotoImage(file='//192.168.4.11/211b076/AP/PROJECT AP/Bus_for_project.png')
Label(root,image=bus).grid(row=0,column=0,columnspan=50,padx=w//3)

Label(root,text='Online Bus Booking System',bg='light blue',fg='red',font='Arial 14 bold').grid(row=1,column=0,columnspan=100,pady=40)
Label(root,text='Bus Ticket').grid(row=2,columnspan=100)

fr=Frame(root,relief='groove',bd=3)
fr.grid(row=4,column=0,columnspan=50,padx=(w/15,0))
Label(fr,text='Passengers :',font='Arial 10 bold').grid(row=3,column=1)
Label(fr,text='Astha Singh',font='Arial 10 bold').grid(row=3,column=2)
Label(fr,text='Gender :',font='Arial 10 bold').grid(row=3,column=4)
Label(fr,text='Female',font='Arial 10 bold').grid(row=3,column=5)
Label(fr,text='No of seats:',font='Arial 10 bold').grid(row=4,column=1)
Label(fr,text='2',font='Arial 10 bold').grid(row=4,column=2)
Label(fr,text='Phone:',font='Arial 10 bold').grid(row=4,column=4)
Label(fr,text='7007055629',font='Arial 10 bold').grid(row=4,column=5)
Label(fr,text='Age :',font='Arial 10 bold').grid(row=5,column=1)
Label(fr,text='20',font='Arial 10 bold').grid(row=5,column=2)
Label(fr,text='Fare Rs :',font='Arial 10 bold').grid(row=5,column=4)
Label(fr,text='1000.00',font='Arial 10 bold').grid(row=5,column=5)
Label(fr,text='Booking Ref :',font='Arial 10 bold').grid(row=6,column=1)
Label(fr,text='3',font='Arial 10 bold').grid(row=6,column=2)
Label(fr,text='Bus Detail :',font='Arial 10 bold').grid(row=6,column=4)
Label(fr,text='Kamla',font='Arial 10 bold').grid(row=6,column=5)
Label(fr,text='Travel on :',font='Arial 10 bold').grid(row=7,column=1)
Label(fr,text='20/11/22',font='Arial 10 bold').grid(row=7,column=2)
Label(fr,text='Booked On :',font='Arial 10 bold').grid(row=7,column=4)
Label(fr,text='12/11/22',font='Arial 10 bold').grid(row=7,column=5)
Label(fr,text='No of Seats:',font='Arial 10 bold').grid(row=8,column=1)
Label(fr,text='2',font='Arial 10 bold').grid(row=8,column=2)
Label(fr,text='Boarding point :',font='Arial 10 bold').grid(row=8,column=4)
Label(fr,text='Guna',font='Arial 10 bold').grid(row=8,column=5)
Label(fr,text='* Total amount of Rs 1000.00/- to be paid at the time of boarding',font='Arial 8').grid(row=9,columnspan=100,pady=10)

showinfo('Success','Seat Booked')
